#### Небольшое задание

- Создайте объект DataFrame и заполните его значениями площадей (в кв.км.) и количеством населения нескольких (не менеее пяти) областей РФ (данные можно брать из открытых источников, например из википедии);
- Рассчитайте плотность населения по каждой области и занесите эти данные в дополнительный столбец созданного вами объекта DataFrame;
- Опробуйте все методы индексирования и создания срезов для объектов DataFrame, которые мы обсудили в данном разделе.

#### Выполнение

In [7]:
# Импорт библиотек
import pandas as pd
import numpy as np

# 1. Создаем объект DataFrame и заполняем его значениями площадей (в кв.км.) 
#    и количеством населения нескольких (не менее пяти) областей РФ.
data = {
    'Новосибирская': {'Население': 2786540, 'Площадь': 177756},
    'Омская': {'Население': 1805500, 'Площадь': 141140},
    'Самарская': {'Население': 3150000, 'Площадь': 53565},
    'Сахалинская': {'Население': 457000, 'Площадь': 87100},
    'Калининградская': {'Население': 1033000, 'Площадь': 15125}
}

# Преобразуем словарь в DataFrame
regions = pd.DataFrame(data).T
regions.index.name = 'Область'
print("Исходные данные по областям:")
display(regions)

# 2. Рассчитайте плотность населения по каждой области и занесите эти данные 
#    в дополнительный столбец созданного вами объекта DataFrame.
regions['Плотность'] = regions['Население'] / regions['Площадь']
print("Данные с рассчитанной плотностью населения (чел/кв.км):")
display(regions)

# 3. Опробуйте все методы индексирования и создания срезов для объектов DataFrame,
#    которые мы обсудили в данном разделе.

print("--- Демонстрация различных методов индексации и срезов ---")

# 3.1. Индексация как в словаре (по названию столбца)
print("\n1. Столбец 'Население':")
print(regions['Население'])

# 3.2. Индексация по атрибуту (по названию столбца)
# русские названия столбцов нельзя использовать через атрибутивный доступ
# Используем обычную индексацию по словарю
print("\n2. Столбец 'Площадь':")
print(regions['Площадь'])

# 3.3. Выборка строк по индексу (названию области) с помощью .loc
print("\n3. Данные только для Новосибирской и Самарской областей (по индексу):")
display(regions.loc[['Новосибирская', 'Самарская']])

# 3.4. Срез строк по индексу (от Омской до Сахалинской)
print("\n4. Срез строк от 'Омская' до 'Сахалинская':")
display(regions.loc['Омская':'Сахалинская'])

# 3.5. Срез по строкам с использованием целочисленного индекса (первые 3 строки)
print("\n5. Первые 3 строки (по iloc):")
display(regions.iloc[:3])

# 3.6. Маскирование — выбор областей с плотностью населения больше 20 чел/кв.км
print("\n6. Области с плотностью > 20 чел/кв.км (булево маскирование):")
display(regions[regions['Плотность'] > 20])

# 3.7. «Прихотливая» индексация — выбор столбцов 'Население' и 'Плотность' для конкретных областей
print("\n7. Столбцы 'Население' и 'Плотность' для Омской и Калининградской областей:")
display(regions.loc[['Омская', 'Калининградская'], ['Население', 'Плотность']])

# 3.8. Срез по строкам и выбор определенных столбцов
print("\n8. Срез строк (первые 3) и выбор столбцов 'Площадь' и 'Плотность':")
display(regions.iloc[:3, [1, 2]])  # 1 - 'Площадь', 2 - 'Плотность'

Исходные данные по областям:

                 Население  Площадь
Область
Новосибирская      2786540   177756
Омская             1805500   141140
Самарская          3150000    53565
Сахалинская         457000    87100
Калининградская    1033000    15125

Данные с рассчитанной плотностью населения (чел/кв.км):

                 Население  Площадь  Плотность
Область
Новосибирская      2786540   177756  15.676208
Омская             1805500   141140  12.792263
Самарская          3150000    53565  58.807057
Сахалинская         457000    87100   5.246843
Калининградская    1033000    15125  68.297521

--- Демонстрация различных методов индексации и срезов ---

1. Столбец 'Население':
Область
Новосибирская      2786540
Омская             1805500
Самарская          3150000
Сахалинская         457000
Калининградская    1033000
Name: Население, dtype: int64

2. Столбец 'Площадь':
Область
Новосибирская      177756
Омская             141140
Самарская           53565
Сахалинская         87100
Калининградская     15125
Name: Площадь, dtype: int64

3. Данные только для Новосибирской и Самарской областей (по индексу):

               Население  Площадь  Плотность
Область
Новосибирская    2786540   177756  15.676208
Самарская        3150000    53565  58.807057

4. Срез строк от 'Омская' до 'Сахалинская':

             Население  Площадь  Плотность
Область
Омская         1805500   141140  12.792263
Самарская      3150000    53565  58.807057
Сахалинская     457000    87100   5.246843

5. Первые 3 строки (по iloc):

               Население  Площадь  Плотность
Область
Новосибирская    2786540   177756  15.676208
Омская           1805500   141140  12.792263
Самарская        3150000    53565  58.807057

6. Области с плотностью > 20 чел/кв.км (булево маскирование):

                 Население  Площадь  Плотность
Область
Самарская          3150000    53565  58.807057
Калининградская    1033000    15125  68.297521

7. Столбцы 'Население' и 'Плотность' для Омской и Калининградской областей:

                 Население  Плотность
Область
Омская             1805500  12.792263
Калининградская    1033000  68.297521

8. Срез строк (первые 3) и выбор столбцов 'Площадь' и 'Плотность':

               Площадь  Плотность
Область
Новосибирская   177756  15.676208
Омская          141140  12.792263
Самарская        53565  58.807057